#!/usr/bin/sh
# ********************************************************************
# Ericsson Radio Systems AB                                     SCRIPT
# ********************************************************************
#
#
# (c) Ericsson Radio Systems AB 2018 - All rights reserved.
#
# The copyright to the computer program(s) herein is the property
# of Ericsson Radio Systems AB, Sweden. The programs may be used 
# and/or copied only with the written permission from Ericsson Radio 
# Systems AB or in accordance with the terms and conditions stipulated 
# in the agreement/contract under which the program(s) have been 
# supplied.
#
# ********************************************************************
# Name    : installed_techpacks
# Date    : 15/07/2020(dummy date) Last modified 10/05/2023
# Purpose : Ericsson Network IQ script for showing installed tech packs
# Usage   : installed_techpacks [-s] [-p] [-v] 
# ********************************************************************

### Function: usage_msg ###
#
#   Print out the usage message
#
# Arguments:
#	none
# Return Values:
#	none
usage_msg() 
{
echo ""
echo "Usage: `basename $0` [-s] | [-p] | [-v] | [-d]"
echo "options:"
echo "-s  : Print out the names of tech packs."
echo "-p  : Print out the product numbers of the tech packs."
echo "-v  : Print out the version numbers of the tech packs."
echo "-d  : Print out the details of the tech packs."
echo "-f  : Print out the Rstates and the names of the features insatlled."
echo "No parameters  : Print out all information about tech packs."
}

if [ ! -r "${CONF_DIR}/niq.rc" ] ; then
  echo "ERROR: Source file is not readable at ${CONF_DIR}/niq.rc"
  exit 2
fi

. ${CONF_DIR}/niq.rc

if [ -z "${CONF_DIR}" ] ; then
  echo "Environment variable CONF_DIR is not set or empty."
  exit 1
fi

if [ -z "$PLATFORM_DIR" ] ; then
    echo "Environment variable PLATFORM_DIR is not set or empty."
    exit 1
fi

if [ -z "$INSTALLER_DIR" ] ; then
    echo "Environment variable INSTALLER_DIR is not set or empty."
    exit 1
fi

if [ -z "$RT_DIR" ] ; then
    echo "Environment variable RT_DIR is not set or empty."
    exit 1
fi

while getopts ":spvdf" Option
do
  case $Option in
    s) SHOW_NAMES="true" 
       ;;
    p) SHOW_PRODUCT_NUMBERS="true" 
       ;;
    v) SHOW_VERSION_NUMBERS="true" 
       ;;
	d) SHOW_DETAILS="true" 
       ;; 
    f) SHOW_FEATURES="true" 
       ;; 
   \?) usage_msg
       exit 1 
       ;;
  esac
done

if [ -z "${SHOW_NAMES}" ]; then
    SHOW_NAMES="false"
fi

if [ -z "${SHOW_PRODUCT_NAMES}" ]; then
    SHOW_PRODUCT_NAMES="false"
fi

if [ -z "${SHOW_VERSION_NUMBERS}" ]; then
    SHOW_VERSION_NUMBERS="false"
fi

if [ -z "${SHOW_DETAILS}" ]; then
    SHOW_DETAILS="false"
fi

if [ -z "${SHOW_FEATURES}" ]; then
    SHOW_DETAILS="false"
fi

CPATH="${INSTALLER_DIR}/lib/installer.jar"
INSTALLER_JARPATH="${CPATH}"

if [ ! -r "${CPATH}" ] ; then
  echo "ERROR: Jar file "installer.jar" is not readable at ${CPATH}"
  exit 2
fi

DIRS=`ls ${PLATFORM_DIR}`

for file in $DIRS
do
  if [ -d ${PLATFORM_DIR}/$file/dclib ]
  then
    JARS=`ls ${PLATFORM_DIR}/$file/dclib/*.jar`

    for jar in $JARS
    do
      CPATH="${CPATH}:${jar}"
    done
  fi
done

CURRENT_WORKING_DIRECTORY=`pwd`

JAVA_HOME=${RT_DIR}/java
export JAVA_HOME

ANT_OPTS="$ANT_OPTS $PF_ANT_OPTS" 
export ANT_OPTS 
# Comments about the sed command after ANT call.
# 1. Drop out lines that do not start with [Get
# 2. Remove all characters before ']'
# 3. Remove all empty lines
# 20110912 EANGUAN :: FOR TR HO68763 :: Adding the installer path as prefix for file tasks_install_utils.xml
${RT_DIR}/ant/bin/ant -f ${INSTALLER_DIR}/tasks_install_utils.xml -lib ${CPATH} -DshowNames=${SHOW_NAMES} -DshowProductNumbers=${SHOW_PRODUCT_NUMBERS} -DshowVersionNumbers=${SHOW_VERSION_NUMBERS} -DshowDetails=${SHOW_DETAILS} -DshowFeatureList=${SHOW_FEATURES} -DconfigurationDirectory=${CONF_DIR} get_installed_tech_packs | sed -e '/^[^\[Get]/ d' -e 's/.*\].//' -e '/^$/ d'
