#!/bin/bash
# ********************************************************************
# Ericsson Radio Systems AB                                     SCRIPT
# ********************************************************************
#
#
# (c) Ericsson Radio Systems AB 2018 - All rights reserved.
#
# The copyright to the computer program(s) herein is the property
# of Ericsson Radio Systems AB, Sweden. The programs may be used 
# and/or copied only with the written permission from Ericsson Radio 
# Systems AB or in accordance with the terms and conditions stipulated 
# in the agreement/contract under which the program(s) have been 
# supplied.
#
# ********************************************************************
# Name    : partition_roll_over
# Date    : 15/07/2020(dummy date) Last modified 10/05/2023
# Purpose : ENIQ script rollover the current partition to next partition for techpack in DWHDB database
# Usage   : partition_roll_over
# ********************************************************************

if [ -z "${CONF_DIR}" ] ; then
  echo "ERROR: CONF_DIR is not set"
  exit 1
fi

if [ ! -r "${CONF_DIR}/niq.rc" ] ; then
  echo "ERROR: Source file is not readable at ${CONF_DIR}/niq.rc"
  exit 2
fi

if [ -z "$1" ] ; then
        TECHPACK_NAME=ALL
        echo ""
        echo "======================================="
        echo "No techpack name specified."
        echo "This means it will be run for all relevant techpacks."
        echo "======================================="
        echo ""
else
        TECHPACK_NAME=$1
        echo ""
        echo "======================================="
        echo "Running for techpack: '$TECHPACK_NAME'."
        echo "======================================="
        echo ""
fi

. ${CONF_DIR}/niq.rc

CPATH="${INSTALLER_DIR}/lib/installer.jar"

DIRS=`ls ${PLATFORM_DIR}`

for file in $DIRS
do
  if [ -d ${PLATFORM_DIR}/$file/dclib ]
  then
    JARS=`ls ${PLATFORM_DIR}/$file/dclib/*.jar`

    for jar in $JARS
    do
      CPATH="${CPATH}:${jar}"
    done
  fi
done

TIMESTAMP=`date +%y.%m.%d_%H:%M:%S`

LOGFILE=${LOG_DIR}/partition_roll_over/partition_roll_over_${TIMESTAMP}.log

HSTNAME=`hostname`

if [ ! -d ${LOG_DIR}/partition_roll_over ] ; then
  mkdir -p ${LOG_DIR}/partition_roll_over
fi

echo "===================================="  | tee -a ${LOGFILE}
echo "Partition Rollover for techpack(s): '$TECHPACK_NAME' in DWHDB database @ ${HSTNAME}" | tee -a ${LOGFILE}
echo "===================================="  | tee -a ${LOGFILE}

echo "Stopping engine" | tee -a ${LOG_FILE}

${BIN_DIR}/engine stop

STOP_EXIT_STATUS=$?

if [ ${STOP_EXIT_STATUS} -ne 0 ] ; then
  echo "Engine could not be stopped. Aborting script." | tee -a ${LOG_FILE}
  exit 43
else
  echo "Engine has stopped successfully at "`date +%Y.%m.%d_%H:%M:%S` | tee -a ${LOG_FILE}
fi

JAVA_HOME=${RT_DIR}/java
export JAVA_HOME

ANT_OPTS="$ANT_OPTS $PF_ANT_OPTS" 
export ANT_OPTS 

cd ${INSTALLER_DIR}; ${RT_DIR}/ant/bin/ant -f ${INSTALLER_DIR}/tasks_partition_roll_over_to_old_techpack.xml -lib ${CPATH} -DconfDirectory=${CONF_DIR} -DtechpackName=${TECHPACK_NAME} partitionRollOver | tee -a ${LOGFILE}

if [ -f ${LOGFILE} ] ; then
  SUC=`cat ${LOGFILE} | grep "BUILD SUCCESSFUL"`
  if [ ! -z "${SUC}" ] ; then
    echo "===================================="  | tee -a ${LOGFILE}
    echo "Successfully Rollover the partition for techpacks in DWHDB database"  | tee -a ${LOGFILE}
    echo "===================================="  | tee -a ${LOGFILE}
  else
    echo "============================="  | tee -a ${LOGFILE}
    echo "Partition Rollover for techpacks in DWHDB database failed"  | tee -a ${LOGFILE}
    echo "============================="  | tee -a ${LOGFILE}
  fi
fi