CREATE TABLE Meta_databases (
	USERNAME VARCHAR(31), 
	VERSION_NUMBER VARCHAR(31),
    TYPE_NAME VARCHAR(31), 
	CONNECTION_ID VARCHAR(31), 
	CONNECTION_NAME VARCHAR(31),
	CONNECTION_STRING VARCHAR(31), 
	PASSWORD VARCHAR(31), 
	DESCRIPTION VARCHAR(31), 
	DRIVER_NAME VARCHAR(31),
    DB_LINK_NAME VARCHAR(31)
);
		  
CREATE TABLE Meta_collection_sets (
	COLLECTION_SET_ID VARCHAR(20), 
	COLLECTION_SET_NAME VARCHAR(20),
	DESCRIPTION VARCHAR(20),
	VERSION_NUMBER VARCHAR(20),
	ENABLED_FLAG VARCHAR(20),
	TYPE VARCHAR(20)
);

CREATE TABLE Meta_collections (
	COLLECTION_ID BIGINT, 
	COLLECTION_NAME VARCHAR(20),
	COLLECTION VARCHAR(20), 
	MAIL_ERROR_ADDR VARCHAR(20), 
	MAIL_FAIL_ADDR VARCHAR(20), 
	MAIL_BUG_ADDR VARCHAR(20),
	MAX_ERRORS BIGINT, 
	MAX_FK_ERRORS BIGINT, 
	MAX_COL_LIMIT_ERRORS BIGINT,
	CHECK_FK_ERROR_FLAG VARCHAR(20), 
	CHECK_COL_LIMITS_FLAG VARCHAR(20), 
	LAST_TRANSFER_DATE TIMESTAMP,
	VERSION_NUMBER VARCHAR(20), 
	COLLECTION_SET_ID BIGINT, 
	USE_BATCH_ID VARCHAR(20), 
	PRIORITY BIGINT,
	QUEUE_TIME_LIMIT BIGINT, 
	ENABLED_FLAG VARCHAR(20), 
	SETTYPE VARCHAR(20), 
	FOLDABLE_FLAG VARCHAR(20),
	MEASTYPE VARCHAR(20), 
	HOLD_FLAG VARCHAR(20), 
	SCHEDULING_INFO VARCHAR(20)
);
			  
CREATE TABLE Alarminterface (
	INTERFACEID VARCHAR(20), 
	DESCRIPTION VARCHAR(20), 
	STATUS VARCHAR(20), 
	COLLECTION_SET_ID BIGINT, 
	COLLECTION_ID BIGINT, 
	QUEUE_NUMBER BIGINT
);
