CREATE TABLE META_DATABASES (
	USERNAME VARCHAR(30),
	VERSION_NUMBER VARCHAR(32),
	TYPE_NAME VARCHAR(15),
	CONNECTION_ID NUMERIC(31),
	CONNECTION_NAME VARCHAR(30),
	CONNECTION_STRING VARCHAR(400),
	PASSWORD VARCHAR(30),
	DESCRIPTION VARCHAR(32000),
	DRIVER_NAME VARCHAR(100),
	DB_LINK_NAME VARCHAR(128)
);
CREATE TABLE META_COLLECTION_SETS (
	COLLECTION_SET_ID NUMERIC(31),
	COLLECTION_SET_NAME VARCHAR(128),
	DESCRIPTION VARCHAR(32000),
	VERSION_NUMBER VARCHAR(32),
	ENABLED_FLAG VARCHAR(1),
	TYPE VARCHAR(32)
);
CREATE TABLE META_SCHEDULINGS (
	VERSION_NUMBER VARCHAR(32),
	ID NUMERIC(31),
	EXECUTION_TYPE VARCHAR(15),
	OS_COMMAND VARCHAR(2000),
	SCHEDULING_MONTH NUMERIC(2),
	SCHEDULING_DAY NUMERIC(2),
	SCHEDULING_HOUR NUMERIC(2),
	SCHEDULING_MIN NUMERIC(2),
	COLLECTION_SET_ID NUMERIC(31),
	COLLECTION_ID NUMERIC(31),
	MON_FLAG VARCHAR(1),
	TUE_FLAG VARCHAR(1),
	WED_FLAG VARCHAR(1),
	THU_FLAG VARCHAR(1),
	FRI_FLAG VARCHAR(1),
	SAT_FLAG VARCHAR(1),
	SUN_FLAG VARCHAR(1),
	STATUS VARCHAR(20),
	LAST_EXECUTION_TIME TIMESTAMP,
	INTERVAL_HOUR NUMERIC(2),
	INTERVAL_MIN NUMERIC(2),
	NAME VARCHAR(128),
	HOLD_FLAG VARCHAR(1),
	PRIORITY NUMERIC(3),
	SCHEDULING_YEAR NUMERIC(4),
	TRIGGER_COMMAND VARCHAR(2000),
	LAST_EXEC_TIME_MS NUMERIC(31)
);
CREATE TABLE META_COLLECTIONS (
	COLLECTION_ID NUMERIC(31),
	COLLECTION_NAME VARCHAR(128),
	COLLECTION VARCHAR(200),
	MAIL_ERROR_ADDR VARCHAR(100),
	MAIL_FAIL_ADDR VARCHAR(100),
	MAIL_BUG_ADDR VARCHAR(100),
	MAX_ERRORS NUMERIC(31),
	MAX_FK_ERRORS NUMERIC(31),
	MAX_COL_LIMIT_ERRORS NUMERIC(31),
	CHECK_FK_ERROR_FLAG VARCHAR(1),
	CHECK_COL_LIMITS_FLAG VARCHAR(1),
	LAST_TRANSFER_DATE TIMESTAMP,
	VERSION_NUMBER VARCHAR(32),
	COLLECTION_SET_ID NUMERIC(31),
	USE_BATCH_ID VARCHAR(1),
	PRIORITY NUMERIC(3),
	QUEUE_TIME_LIMIT NUMERIC(31),
	ENABLED_FLAG VARCHAR(1),
	SETTYPE VARCHAR(10),
	FOLDABLE_FLAG VARCHAR(1),
	MEASTYPE VARCHAR(30),
	HOLD_FLAG VARCHAR(1),
	SCHEDULING_INFO VARCHAR(2000)
);
CREATE TABLE META_TRANSFER_ACTIONS (
	VERSION_NUMBER VARCHAR(32),
	TRANSFER_ACTION_ID NUMERIC(31),
	COLLECTION_ID NUMERIC(31),
	COLLECTION_SET_ID NUMERIC(31),
	ACTION_TYPE VARCHAR(20),
	TRANSFER_ACTION_NAME VARCHAR(128),
	ORDER_BY_NO NUMERIC(31),
	DESCRIPTION VARCHAR(32000),
	WHERE_CLAUSE_01 VARCHAR(32000),
	ACTION_CONTENTS_01 VARCHAR(32000),
	ENABLED_FLAG VARCHAR(1),
	CONNECTION_ID NUMERIC(31),
	WHERE_CLAUSE_02 VARCHAR(32000),
	WHERE_CLAUSE_03 VARCHAR(32000),
	ACTION_CONTENTS_02 VARCHAR(32000),
	ACTION_CONTENTS_03 VARCHAR(32000)
);
CREATE TABLE DataInterface (
	INTERFACENAME VARCHAR(255),
	STATUS NUMERIC(9),
	INTERFACETYPE VARCHAR(50),
	DESCRIPTION VARCHAR(32000),
	DATAFORMATTYPE VARCHAR(50),
	INTERFACEVERSION VARCHAR(32),
	LOCKEDBY VARCHAR(255),
	LOCKDATE TIMESTAMP,
	PRODUCTNUMBER VARCHAR(255),
	ENIQ_LEVEL VARCHAR(12),
	RSTATE VARCHAR(255),
	INSTALLDESCRIPTION VARCHAR(32000)
);
CREATE TABLE InterfaceTechpacks (
	INTERFACENAME VARCHAR(255),
	TECHPACKNAME VARCHAR(30),
	TECHPACKVERSION VARCHAR(32),
	INTERFACEVERSION VARCHAR(32)
);
CREATE TABLE TPActivation (
	TECHPACK_NAME VARCHAR(30),
	STATUS VARCHAR(10),
	VERSIONID VARCHAR(128),
	TYPE VARCHAR(10),
	MODIFIED INTEGER
);
CREATE TABLE TypeActivation (
	TECHPACK_NAME VARCHAR(30),
	STATUS VARCHAR(10),
	TYPENAME VARCHAR(255),
	TABLELEVEL VARCHAR(50),
	STORAGETIME NUMERIC(15),
	TYPE VARCHAR(12),
	PARTITIONPLAN VARCHAR(128)
);
CREATE TABLE DataFormat (
	DATAFORMATID VARCHAR(100),
	TYPEID VARCHAR(255),
	VERSIONID VARCHAR(128),
	OBJECTTYPE VARCHAR(255),
	FOLDERNAME VARCHAR(128),
	DATAFORMATTYPE VARCHAR(50)
);
CREATE TABLE DefaultTags (
	TAGID VARCHAR(128),
	DATAFORMATID VARCHAR(100),
	DESCRIPTION VARCHAR(200)
);
CREATE TABLE InterfaceMeasurement (
	TAGID VARCHAR(128),
	DATAFORMATID VARCHAR(100),
	INTERFACENAME VARCHAR(255),
	TRANSFORMERID VARCHAR(255),
	STATUS NUMERIC(9),
	MODIFTIME TIMESTAMP,
	DESCRIPTION VARCHAR(32000),
	TECHPACKVERSION VARCHAR(32),
	INTERFACEVERSION VARCHAR(32)
);
CREATE TABLE Transformer (
	TRANSFORMERID VARCHAR(255),
	VERSIONID VARCHAR(128),
	DESCRIPTION VARCHAR(32000),
	TYPE VARCHAR(50)
);